[log]
  level = "DEBUG"

[providers.docker]
  exposedByDefault = false
  endpoint = "unix:///var/run/docker.sock"
  network = "rtraefik-public"
  swarmMode = true

[api]
  dashboard = true
  insecure = true
  debug = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"
    
# [certificatesResolvers]
#   [certificatesResolvers.default.acme]
#     email = "tuan-linh.tran@ant-tech.eu"
#     storage = "acme.json"
#     [certificatesResolvers.default.acme.tlsChallenge]